version: '3'
services:
  mysql_container:
    image: mysql
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE=myprofile
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_password
  profile-application:
    build: .
    ports:
      - 7000:7000
    environment:
      - HOST_NAME=mysql_container
      - DB_NAME=myprofile
      - USER_NAME=root
    secrets:
      - db_password
volumes:
  db_data:
    driver: local
secrets:
  db_password:
    file: ./mysql_password.txt